config/routes.rb
PairFit::Application.routes.draw do

  root                'sessions#new'
  get    'signup'  => 'users#new'
  resources :users do
    get "dashboard", on: :member
    get "buddies", on: :member
    get "schedule", on: :member
    get "buddies", on: :member
    get "buddy_page", on: :member
    get "workouts", on: :member
    get 'edit_activities', on: :member
    patch 'update_activities', on: :member
    resources :user_activities
    resources :user_marks
    resources :user_workouts
  end

  resources :users

  resources :partnerships
  resources :user_marks
  resources :user_activities
  resources :user_workouts
  get  'static_pages/user_profile'
  get  'static_pages/user_profile2'
  get  'static_pages/find_buddy'
  get  'static_pages/search_results'
  get  'static_pages/buddy_page'
  get  'static_pages/buddies'
  get  'static_pages/schedule'
  get  'static_pages/dashboard'
  get  'static_pages/search_results_B'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/static_pages_controller.rb
include WoopraRailsSDK

class StaticPagesController < ApplicationController

  # GET /static_pages
  # GET /static_pages.json
  layout "static_page"

  def home
    @user = nil
  end
  
  def user_profile
    
  end
  
  def user_profile2
    
  end
  
  def find_buddy
    
  end
  
  def search_results
    woopra = WoopraTracker.new(request)
    woopra.config({
      domain: "pairfit.herokuapp.com",
      idle_timeout: 15000})
    woopra.track("a_version_time_elapsed")

    @woopra_code = woopra.js_code
    @users = User.all
  end
  
  def buddy_page
    
  end

  def buddies

  end

  def schedule

  end

  def dashboard

  end

  def search_results_B
    woopra = WoopraTracker.new(request)
    woopra.config({
      domain: "pairfit.herokuapp.com",
      idle_timeout: 15000})
    woopra.track("b_version_time_elapsed")

    @woopra_code = woopra.js_code
    @users = User.all
  end

 
  private


    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params[:static_page]
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_user_row.html.erb
<tr>
  <td class="left">
    <%= link_to user do %>
            <span class="buddy-box">
              <%= image_tag 'http://www.northleach.gov.uk/wp-content/uploads/2013/12/blank-avatar-220x220.png', class: 'bud profile-pic' %>
              <br>
              <%= user.name %>
            </span>
    <% end %>
  </td>
  <td class="middle">
          <span class="buddy-box">
          <%= user.bio %>
          </span>
  </td>
</tr>

    

app/views/static_pages/_user_row_B.html.erb
<div class="col-xs-4 text-center users">
    <%= link_to user do %>
       <div class="buddy-box" data-toggle="modal" data-target="#user-<%= user.id %>-Modal">
          <%= image_tag 'profile.png', class: 'bud profile-pic' %>
          <br>
          <%= user.name %>
       </div>
    <% end %>
</div>

<!-- Modal -->
  <div class="modal fade" id="user-<%= user.id %>-Modal" tabindex="-1" role="dialog" aria-labelledby="user<%= user.id %>-Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h3 class="modal-title" id="user<%= user.id %>-Label"><%= user.name %></h3>	
        </div>
        <div class="modal-body">
          <h5 align="center">
          	<%= user.bio %>
          </h5>
          <div class="row">
            <div class="activity-box">
            <% user.activities.each do |a| %>
              <a href="javascript:;" class="activity-button" id="<%= a.name.delete(' ') %>">
                <%= image_tag(a.name.delete(' ') + '.png', class: "activity-badge") %>
              </a>
            <% end %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= link_to user do %>
          	<button type="button" class="btn btn-default viewProfButton"><h4>View Profile</h4></button>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/static_pages/buddies.html.erb
<div class="outer">
<section>
      <h1>This will have a page of all your buddies</h1>
</section>
</div>

app/views/static_pages/buddy_page.html.erb
<div class="outer" id="full">
  <div class="col-cont"> 
    <div id="left" class="col">
      <h1>Andrew</h1>
      <%= image_tag 'profile.jpg', class: 'me profile-pic' %>
    </div><div id="right" class="col">
      <h1>John</h1>
      <%= image_tag 'http://www.northleach.gov.uk/wp-content/uploads/2013/12/blank-avatar-220x220.png', class: 'me profile-pic' %>
    </div>   
  </div>   
    
</div>

app/views/static_pages/find_buddy.html.erb
    <div class="title">
      <div class="row text-center">
        <h1>Find a Buddy</h1>
      </div>
    </div>
    <table class="form">
      <tr>
        <td class="left">
          What activity do you want a buddy for?
        </td>
        <td class="right">
         <select>
           <option>Running</option>
           <option>Lifting</option>
           <option>Cycling</option>
           <option>Walking</option>
           <option>Swimming</option>
           <option>Hiking</option>
           <option>Other</option>
         </select>
        </td>
      </tr>
      <tr>
      <tr>
        <td class="left">
          Do you want to meet up with your buddy in person?
        </td>
        <td class="right">
         <select>
           <option>Yes</option>
           <option>No</option>
         </select>
        </td>
      </tr>
      <tr>
        <td class="left">
          Preferred Sex of Buddy
        </td>
        <td class="right">
         <select>
           <option>Male</option>
           <option>Female</option>
           <option>Don't Care</option>
         </select>
        </td>
      </tr>      
      <tr>
        <td class="left">
          How skilled do you want your partner to be compared to your own skill?
        </td>
        <td class="right">
         <select>
           <option>More</option>
           <option>Equally</option>
           <option>Less</option>
         </select>
        </td>
      </tr>  
      
      
    </table>

    <!--
    <%=
      num = rand(0..9)
      if num > 4
        link_to static_pages_search_results_path do
          "View Matches"
        end
      else 
        link_to static_pages_search_results_B_path  do
          "View Matches"
        end
      end
    %> -->

    <%= link_to static_pages_search_results_B_path do %>
      <div class="text-center">
        <span class="link-button">
          View Matches
        </span>
      </div>
    <% end %>

app/views/static_pages/home.html.erb
<div class="box">
  <div id="big-logo">

    <%= image_tag "pear1.png" %>

    <span id="pairfit">PAIRFIT</span>

  </div>

  <%= form_for User.new, html: { class: "login" } do |f| %>
    <%= f.text_field :email, id: "email", placeholder: "Email" %>
    <%= f.text_field :email, id: "pw", placeholder: "Password" %>
    <%= f.submit "log in" %>

    <div id="new-user">
      <%=link_to "New user? Sign up now!", new_user_path %>
    </div>

<% end %>




</div>






<!--<div class="jumbotron home-bg">
    <div class="container"></div>
</div>
  <section>
        <div class="container">
            <div class="row text-center">
                <div class="col-md-4 col-sm-6">
                    <h3>Profile</h3>
                    <#%= link_to image_tag("profile.png", width: "200", class:"img-responsive center-block"), static_pages_user_profile_path %>
                </div>
                <div class="col-md-4 col-sm-6">
                    <h3>Buddies</h3>
                    <#%= link_to image_tag("buddies.png", width: "200", class:"img-responsive center-block"), static_pages_buddies_path %>
                </div>
                <div class="col-md-4 col-sm-6">
                    <h3>Schedule</h3>
                    <#%= image_tag "random.png", width: "200", class:"img-responsive center-block" %>
                </div>
            </div>
        </div>
  </section>
  <section class="success" id="dashboard">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2>Last Workout</h2>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h1>5 mile Run <small>La Jolla Cove</small></h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>-->


    <!-- Main jumbotron for a primary marketing message or call to action -->
 <!--   <div class="jumbotron">
      <div class="container">
        <div class="col-md-6 col-md-offset-3 text-center">
        	<h1>Welcome Back, [User's Name]</h1>
        </div>
      </div>
    </div>

    <section>
        <div class="container">-->
<!--            <div class="row text-center">
                <div class="col-md-3 col-sm-6">
                    <h3>Profile</h3>
                    <#%= image_tag "profile.png", class:"img-responsive center-block" %>
                </div>
                <div class="col-md-3 col-sm-6">
                    <h3>Buddies</h3>
                    <#%= image_tag "buddies.png", class:"img-responsive center-block" %>
                </div>
                <div class="col-md-3 col-sm-6">
                    <h3>Rank</h3>
                    <#%= image_tag "rank.png", class:"img-responsive center-block" %>
                </div>
                <div class="col-md-3 col-sm-6">
                    <h3>Schedule</h3>
                    <#%= image_tag "random.png", class:"img-responsive center-block" %>
                </div>
            </div>
        </div>
    </section>-->

  <!--  <section class="success" id="dashboard">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 text-center" style="border-right: solid;">
                    <h2>Last Workout</h2>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h1>5 mile Run <small>La Jolla Cove</small></h1>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 text-center" style="border-left: solid;">
                    <h2>Points</h2>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h1>500</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>-->

app/views/static_pages/schedule.html.erb
<div class="outer">
<section>
      <h1>This will have a page of all your scheduled workouts</h1>
</section>
</div>

app/views/static_pages/search_results.html.erb
<div class="outer">
  <section>
    <h1>Match Results</h1>
      <%= link_to static_pages_find_buddy_path  do %>
        <span class="link-button">
          < Go Back
        </span>
      <br>
      <br>
      <% end %>    
    
    <table class="results">
      <%= render partial: "user_row", collection: @users, as: 'user' %>
    </table>
  </section>
</div>

app/views/static_pages/search_results_B.html.erb
<div class="outer">
    <div class="title">
      <div class="row text-center">
        <h1>Search Results</h1>
      </div>
    </div>
  <section class="text-center">
      <%= link_to static_pages_find_buddy_path  do %>
        <span class="link-button">
          Go Back
        </span>
      <br>
      <br>
      <% end %>  
      <div class="row">  
        <%= render partial: "user_row_B", collection: @users, as: 'user' %>
      </div>
  </section>
</div>

<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script type="text/javascript">
        $(document).ready(function(){
        $('[data-toggle="popover"]').popover();   
        });
</script>

app/views/static_pages/user_profile.html.erb
<div class="outer">
    <h1>Andrew Simon's Profile</h1>
    <%= image_tag 'profile.jpg', class: 'me profile-pic' %>
  </section>
  <section>
    <h3>Buddies</h3>
      <span class="buddy-box">
        <%= image_tag 'http://www.northleach.gov.uk/wp-content/uploads/2013/12/blank-avatar-220x220.png', class: 'bud profile-pic' %>
        <br>
        John Smith
      </span>
</div>

app/views/static_pages/user_profile2.html.erb
<div class="outer">
  <section>
    <h1>John Smith's Profile</h1>
    <%= image_tag 'http://www.northleach.gov.uk/wp-content/uploads/2013/12/blank-avatar-220x220.png', class: 'me profile-pic' %>
  </section>
  <section>
    <h3>Buddies</h3>
      <span class="buddy-box">
        <%= image_tag 'profile.jpg', class: 'bud profile-pic' %>
        <br>
        Andrew Simon
      </span>
  </section>

</div>