config/routes.rb
PairFit::Application.routes.draw do

  root                'sessions#new'
  get    'signup'  => 'users#new'
  resources :users do
    get "dashboard", on: :member
    get "buddies", on: :member
    get "schedule", on: :member
    get "buddies", on: :member
    get "buddy_page", on: :member
    get "workouts", on: :member
    get 'edit_activities', on: :member
    patch 'update_activities', on: :member
    resources :user_activities
    resources :user_marks
    resources :user_workouts
  end

  resources :users

  resources :partnerships
  resources :user_marks
  resources :user_activities
  resources :user_workouts
  get  'static_pages/user_profile'
  get  'static_pages/user_profile2'
  get  'static_pages/find_buddy'
  get  'static_pages/search_results'
  get  'static_pages/buddy_page'
  get  'static_pages/buddies'
  get  'static_pages/schedule'
  get  'static_pages/dashboard'
  get  'static_pages/search_results_B'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :bio, length: { maximum: 140 }
  validates :location, presence: true, length: { maximum: 255 }

  has_many :partnerships
  has_many :partners, :through => :partnerships
  has_many :inverse_partnerships, :class_name => "Partnership", :foreign_key => "partner_id"
  has_many :inverse_partners, :through => :inverse_partnerships, :source => :user

  has_many :activities, through: :user_activities
  has_many :user_activities

  has_many :marks, through: :user_marks
  has_many :user_marks

  has_many :workouts, through: :user_workouts
  has_many :user_workouts

  def add_activity(activity)
    self.activity_associations.build(activity: activity)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def user_mark(mark)
    UserMark.where(user_id: self.id, mark_id: mark.id).last
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @user.activities.build(params[:activity_ids])
      log_in @user

      flash[:success] = "Welcome to PairFit!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit_activities
    @user = User.find(params[:id])
  end

  def update_activities
    @user = User.find(params[:id])

      @user.user_activities.destroy_all

      params[:user][:activity_ids].each do |a|
        @user.user_activities.create(user_id: @user.id, activity_id: a)
      end

      flash[:success] = "Added activitiy"
      redirect_to @user

  end

  def buddies
    @buddies = current_user.partners.all
  end

  def buddy_page
    @buddy = User.find(params[:id])
  end

  def workouts
    @user = User.find(params[:id])
  end

  def add_workout
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :location, :bio, :email, :password, :age, :weight, :height,
                                 :password_confirmation, :activity_ids => [] )
  end

  def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/views/users/_buddy.html.erb
<%= link_to buddy_page_user_path(buddy) do %>
  <span class="buddy-cont">
              <%= image_tag 'http://www.northleach.gov.uk/wp-content/uploads/2013/12/blank-avatar-220x220.png', class: 'bud profile-pic' %>
    <br>
    <%= buddy.name %>
  </span>
<% end %>

app/views/users/buddies.html.erb
<div class="title">
	<div class="row text-center">
		<h1>Your Buddies</h1>
	</div>
</div>

<%= render partial: "buddy", collection: @buddies, as: 'buddy' %>

app/views/users/buddy_page.html.erb
<div class="outer" id="full">
  <div class="next-workout white-box">
    Next Workout: 2/27/15
    <br>
    Running at 3:00 p.m.
  </div>
  <div class="challenge white-box">
    <h5>WEEKLY CHALLENGE: RUN 20 MILES</h5>
    <div class="bar-cont">
      <div class="bar">
      </div>
    </div>

    <div class="prog">
      <span class="left">
        13 mi.
      </span>
      <span class="right">
        2 mi.
      </span>
    </div>

  </div>
  <div class="col-cont">
    <div id="left" class="col">

      <%= image_tag 'profile.jpg', class: 'me profile-pic' %>
      <h1>Andrew</h1>
    </div><div id="right" class="col">

    <%= image_tag 'http://www.northleach.gov.uk/wp-content/uploads/2013/12/blank-avatar-220x220.png', class: 'me profile-pic' %>
    <h1>John</h1>
  </div>
  </div>

</div>

app/views/users/dashboard.html.erb
<div class="outer">
	<div class="jumbotron">
		<h2 class="text-center">Next Workout</h2>
		<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Thursday Feb 12- 5PM
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        Running with John Smith
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Friday Feb 13 - 2:30PM
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Sunday, Feb 15 - 10AM 
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
      </div>
    </div>
  </div>
</div> 
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<!-- This is how the user can edit his/her profile -->
<div class="over"></div>
  <div class="prof-box">
    <div class="col-sm-6 col-sm-offset-3">
      <h1 class="text-center">Update Your Information</h1>
      <hr>
      <div class="text-center">
        <%= link_to "Go Back", current_user, class: "link-button"%>
      </div>
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :age %>
        <%= f.text_field :age, class: 'form-control' %>

        <%= f.label :location %>
        <%= f.text_field :location, class: 'form-control' %>

        <%= f.label :weight, "Weight (Don't worry! This is private information)" %>
        <%= f.text_field :weight, class: 'form-control' %>

        <%= f.label :height, "Height (Don't worry! This is private information)" %>
        <%= f.text_field :height, class: 'form-control' %>

        <%= f.label :bio %>
        <%= f.text_field :bio, class: 'form-control' %>

        <br>
        <h4 align="center">Type current password before saving</h4>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <div class="text-center">
          <%= f.submit "Save changes", class: "link-button" %>
        </div>

      <% end %> 
    </div>
  </div>
</div>

app/views/users/edit_activities.html.erb
<div class="title">
	<div class="row text-center">
		<h1>Edit Your Activities</h1>
	</div>
</div>
<div class="text-center">
	<br>
	<%= link_to current_user do%>
		<span class="link-button">
			Back to Profile
		</span>
	<% end %>
</div>
<div class="text-center">
<%= form_for @user, url: {action: 'update_activities' }, method: :patch do |f| %>|
  <table>
    <%= f.collection_check_boxes(:activity_ids, Activity.all, :id, :name ) do |b| %>
      <tr>
        <td><%= b.label %></td>
        <td><%= b.check_box %></td>
      </tr>
    <% end %>
  </table>
  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/users/new.html.erb
<div class="box">
<% provide(:title, 'Sign up') %>

<h1 class="top">Sign up</h1>
  <%= form_for(@user, html: {class:"sign-up"}) do |f| %>
    <div class="slide-container">
      <div class="slide">
        <h3 class="sign-up-step">CREATE AN ACCOUNT</h3>
          <div>
            <h4>Note: Password must be at least six characters</h4>
            <%= f.text_field :name, placeholder: "Name" %>
            <%= f.email_field :email, placeholder: "Email" %>
            <%= f.password_field :password, placeholder: "Password" %>
            <%= f.password_field :password_confirmation, placeholder: "Retype password" %>
          </div>
          <%= link_to "Next >", "#", class: "next"%>
        </div>
        <div class="slide">
          <h3 class="sign-up-step">ABOUT YOU</h3>
            <div>
              <%= f.number_field :age, placeholder: "Age" %>
              <%= f.number_field :height, placeholder: "Height (inches)" %>
              <%= f.number_field :weight, placeholder: "Weight (pounds)" %>
              <%= f.select(:gender, [['Male', 'M'], ['Female', 'F'], ['Other', 'O']], placeholder: "Gender") %>
              <%= f.text_field :location, placeholder: "Location (City or Zipcode)" %>
              <%= f.text_area :bio, placeholder: "Short bio (140 characters)" %>
            </div>
            <%= link_to "< Back", "#", class: "prev"%>
            <%= link_to "Next >", "#", class: "next"%>
        </div>
        <div class="slide">
          <h3 class="sign-up-step">SELECT YOUR ACTIVITIES</h3>
          <%= render 'shared/error_messages' %>
          <div>
            <table>
            <%= f.collection_check_boxes(:activity_ids, Activity.all, :id, :name ) do |b| %>
              <tr>
                <td><%= b.label %></td>
                <td><%= b.check_box %></td>
              </tr>
            <% end %>
            </table>
          </div>
          <%= link_to "< Back", "#", class: "prev"%>
          <%= f.submit "Create my account" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/schedule.html.erb
<div class="outer">
	<div id='calendar'></div>
</div>

app/views/users/show.html.erb
<!-- This will be future profile -->
<div class="over"></div>

<div class="prof-box">
  <div class="prof">
    <div class="top-box">

      <!-- Left -->
      <div class="person-box">
        <!-- Profile Image -->
        <%= image_tag "profile.png", class: "prof-img" %>
        <br>
        <span class="name"><%= @user.name %></span>
        <br>
        <span class="age">
          <%= @user.age %>
        </span>
        &middot
        <span class="location">
          <%= @user.location %>
        </span>
      </div>

      <div class="slide-container">

        <div class="slide">
          
          <% if !current_user?(@user) %>
          <a href="javascript:;" class="add-buddy-button next">
            <div class="add-buddy">
              <span>+</span>
            </div>
          </a>
          <a href="/static_pages/search_results_B/" class="add-buddy-button">
            <div class="go-back">
              <span><</span>
            </div>
          </a>
          <% end %>

          <div class="activity-box">
            <% @user.activities.each do |a| %>
              <a href="javascript:;" class="activity-button" id="<%= a.name.delete(' ') %>">
                <%= image_tag(a.name.delete(' ') + '.png', class: "activity-badge") %>
              </a>
            <% end %>
            <br>
            <br>
            <% if current_user?(@user) %>
                <%= link_to "Edit Activities", edit_activities_user_path(@user), class: "link-button" %>
                <%= link_to "Edit Profile", edit_user_path(current_user), class: "link-button" %>
            <% end %>
            <% @user.activities.each do |a| %>
              <div class="activity-info" id="<%= a.name.delete(' ') %>">
                <div class="activity-heading"><h5><%= a.name.upcase %></h5></div>
                <table>
                  <% a.marks.each do |m| %>
                    <tr>
                      <td>
                        <%= m.name %>:
                      </td>
                      <td>
                        <% unless @user.user_mark(m).nil? %>
                          <%= @user.user_mark(m).amount %>
                        <% end %>
                      </td>
                      <td>
                          <%= link_to "New Personal Best", new_user_user_mark_path(user_id: @user.id,  mark: m, activity: a) %>
                      </td>
                    </tr>
                  <% end %>
                </table>
              </div>
            <% end %>
          </div>
          <!-- Location -->
          <div class="col-lg-8 col-sm-8 col-lg-offset-2 col-sm-offset-2">
            <div class="bio text-center">
              <h5>ABOUT ME</h5>
              <%= @user.bio %>
            </div>
            <div class="bio text-center">
              <h5>GOALS</h5>
            </div>  
<!--            <div class="bio text-center">
              <h5>ACTIVITIES</h5>

            </div>-->
            <div class="bio text-center">
              <h5>BUDDIES</h5>
              <table class="small-buddies">
                <% for partnership in @user.partnerships %>
                  <tr>
                    <td>
                      <%= link_to buddy_page_user_path(partnership.partner) do %>
                        <span class="buddy-box">
                          <%= image_tag 'http://www.northleach.gov.uk/wp-content/uploads/2013/12/blank-avatar-220x220.png', class: 'bud profile-pic text-center'%>
                           <br>
                           <%= partnership.partner.name %>
                        </span>
                      <% end %>
                    </td>
                    <% if current_user?(@user) %>
                    <td>
                      (<%= link_to "remove", partnership, :method => :delete %>)
                    </td>
                    <% end %>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>

        </div>
        <div class="slide">
          <div class="add-confirmation">
            <div>
              Add <%= @user.name %> as a partner?
            </div>
            <div class="buttons">

              <%= link_to partnerships_path(:partner_id => @user), :method => :post do %>
                <span class="button">Yes!</span>
              <% end %>

              <a href="javascript:;" class="prev"><span class="button">Go back</span></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/workouts.html.erb
<div class="title">
	<div class="row text-center">
		<h1>Your Workouts</h1>
	</div>
	<a href="javascript:;" class="add-buddy-button next">
        <div class="add-buddy">
            <span>+</span>
        </div>
    </a>
</div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Thursday -- Mar 12
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <div class="text-center">
        	<h2>3 Mile Run</h2>
        	<h4>5PM - 5:30 PM</h4>
        	<h4>La Jolla Shores</h4>
        </div>
        <div class="row workout-icons">
        	<div class="col-xs-6 text-center">
        		<i class="fa fa-user fa-2x"> <h4>Pritika</h4></i>
        	</div>
        	<div class="col-xs-6 text-center">
        		<i class="fa fa-envelope fa-2x"> <h4>Message</h4></i>
        	</div>
        </div>
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Friday -- Feb 13
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
      </div>
    </div>
  </div>
  <div class="panel">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Sunday -- Feb 15 
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
      </div>
    </div>
  </div>
</div> 