config/routes.rb
PairFit::Application.routes.draw do

  root                'sessions#new'
  get    'signup'  => 'users#new'
  resources :users do
    get "dashboard", on: :member
    get "buddies", on: :member
    get "schedule", on: :member
    get "buddies", on: :member
    get "buddy_page", on: :member
    get "workouts", on: :member
    get 'edit_activities', on: :member
    patch 'update_activities', on: :member
    resources :user_activities
    resources :user_marks
    resources :user_workouts
  end

  resources :users

  resources :partnerships
  resources :user_marks
  resources :user_activities
  resources :user_workouts
  get  'static_pages/user_profile'
  get  'static_pages/user_profile2'
  get  'static_pages/find_buddy'
  get  'static_pages/search_results'
  get  'static_pages/buddy_page'
  get  'static_pages/buddies'
  get  'static_pages/schedule'
  get  'static_pages/dashboard'
  get  'static_pages/search_results_B'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Pritika Natraj">

    <title>Pairfit|Home</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="css/custom.css" rel="stylesheet">

    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Galindo|Montserrat+Alternates:400,700|Capriola|Varela+Round|Signika:400,600,700' rel='stylesheet' type='text/css'>

    <link rel='stylesheet' href='fullcalendar/fullcalendar.css' />
    <script src='lib/jquery.min.js'></script>
    <script src='lib/moment.min.js'></script>
    <script src='fullcalendar/fullcalendar.js'></script>
</head>
<body>
  <div id="sidebar">
    <% if logged_in? %>
      <span id="logged-in-as">Logged in as <%= current_user.name %></span>
      <ul>
        <li>
          <%= link_to workouts_user_path(current_user) do %>
            <span class="link">Workouts</span>
          <% end %>
        </li>

        <li>
          <%= link_to current_user do %>
            <span class="link">Profile</span>
          <% end %>
        </li>

        <li>
          <%= link_to buddies_user_path(current_user)  do %>
            <span class="link">Buddies</span>
          <% end %>
        </li>

        <li>
          <%= link_to static_pages_find_buddy_path  do %>
            <span class="link">Find a Buddy</span>
          <% end %>
        </li>

        <li>
          <%= link_to 'javascript:;' do %>
            <span class="link">Messages</span>
          <% end %>
        </li>

        <li>
          <%= link_to logout_path, method: "delete" do %>
            <span class="link">Sign out</span>
          <% end %>
        </li>

      </ul>
    <% else %>
      <ul>
        <li>
          <%= link_to root_url  do %>
            <span class="link">Log In</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_path  do %>
            <span class="link">Sign Up!</span>
          <% end %>
        </li>
      </ul>
    <% end %>


  </div>
  <div id="navbar">

    <a href="javascript:;" id="menu">
      <%= image_tag 'menu.png' %>
    </a>
    <span class="pairfit">
      PAIRFIT
    </span>
  </div>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="big-box">
    <%= yield %>
  </div>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/custom.js"></script>

    <script>
    $(document).ready(function() {

      // page is now ready, initialize the calendar...

        $('#calendar').fullCalendar({
        // put your options and callbacks here
        })
    });
  </script>
</body>
</html>

app/views/layouts/static_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Pritika Natraj">

    <title>Pairfit|Home</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <link href="css/custom.css" rel="stylesheet">

    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <link rel='stylesheet' href='fullcalendar/fullcalendar.css' />
    <script src='lib/jquery.min.js'></script>
    <script src='lib/moment.min.js'></script>
    <script src='fullcalendar/fullcalendar.js'></script>

    <%= @woopra_code %>
</head>
<body>
    <div id="sidebar">
    <% if logged_in? %>
      <span id="logged-in-as">Logged in as <%= current_user.name %></span>
      <ul>
        <li>
          <%#= link_to static_pages_dashboard_path  do %>
          <%# end %>
          <%#= link_to "Dashboard", dashboard_user_path(current_user), :class=>"link"%>
          <%= link_to dashboard_user_path(current_user) do %>
            <span class="link">Dashboard</span>
          <% end %>
        </li>

        <li>
          <%= link_to current_user do %>
            <span class="link">Profile</span>
          <% end %>
        </li>

        <li>
          <%= link_to buddies_user_path(current_user)  do %>
            <span class="link">Buddies</span>
          <% end %>
        </li>

        <li>
          <%= link_to static_pages_find_buddy_path  do %>
            <span class="link">Find a Buddy</span>
          <% end %>
        </li>

        <li>
          <%= link_to schedule_user_path(current_user)  do %>
            <span class="link">Schedule</span>
          <% end %>
        </li>

        <li>
          <%= link_to 'javascript:;' do %>
            <span class="link">Messages</span>
          <% end %>
        </li>

        <li>
          <%= link_to logout_path, method: "delete" do %>
            <span class="link">Sign out</span>
          <% end %>
        </li>

      </ul>
    <% else %>
      <ul>
        <li>
          <%= link_to root_url  do %>
            <span class="link">Log In</span>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_path  do %>
            <span class="link">Sign Up!</span>
          <% end %>
        </li>
      </ul>
    <% end %>


  </div>
  <div id="navbar">

    <a href="javascript:;" id="menu">
      <%= image_tag 'menu.png' %>
    </a>
    <span class="pairfit">
      PAIRFIT
    </span>
  </div>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="big-box">
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/custom.js"></script>

    <script>
    $(document).ready(function() {

      // page is now ready, initialize the calendar...

        $('#calendar').fullCalendar({
        // put your options and callbacks here
        })
    });
  </script>
</body>
</html>